openapi: 3.0.3
info:
  title: EQM-B API
  version: 1.0.2
paths:
  /api/v1/posts:
    post:
      summary: Add data to the database
      description: Add data to the database with a valid token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TPost'
      responses:
        '201':
          description: Data added successfully
        '400':
          description: Bad request, invalid data provided
        '403':
          description: Forbidden, token not provided or invalid
        '500':
          description: Internal server error

    get:
      summary: Get data from the database
      description: Get data from the database with a valid token. Supports pagination.
      parameters:
        - in: query
          name: limit
          description: The maximum number of items to return (default is 20).
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - in: query
          name: offset
          description: The number of items to skip.
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: Retrieved data successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TPost'
        '403':
          description: Forbidden, token not provided or invalid
        '500':
          description: Internal server error

    delete:
      summary: Delete posts from the database by ID(s) or title
      description: Delete posts from the database with a valid token by providing one or more IDs (e.g., "1,2,3" or "1-10") or a title.
      parameters:
        - in: query
          name: post_id
          description: One or more IDs to be deleted (e.g., "1,2,3" or "1-10")
          schema:
            type: string
            pattern: '^(\d+(-\d+)?,)*\d+(-\d+)?$'
        - in: query
          name: title
          description: Title of the post to be deleted
          schema:
            type: string
      responses:
        '200':
          description: Posts deleted successfully
        '400':
          description: Invalid request, no valid ID(s) or title provided
        '403':
          description: Forbidden, token not provided or invalid
        '404':
          description: One or more posts not found
        '500':
          description: Internal server error
    put:
      responses:
        '405':
          description: Method Not Allowed
    patch:
      responses:
        '405':
          description: Method Not Allowed
    options:
      responses:
        '405':
          description: Method Not Allowed
    head:
      responses:
        '405':
          description: Method Not Allowed
    trace:
      responses:
        '405':
          description: Method Not Allowed
security:
  - tokenAuth: []
components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    TPost:
      type: object
      required:
        - Source
        - Title
        - Text
      properties:
        Source:
          type: string
        Title:
          type: string
        Text:
          type: string
        Picture:
          type: string
          format: base64
